name: Post coverage comment

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  test:
    name: Publish coverage Comment
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    permissions:
      actions: read
      pull-requests: write
      contents: write
    steps:
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@729e5538c7cb5a0574820d172c55efc17e1da5b9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COVERAGE_PATH: subdir
          SUBPROJECT_ID: "my-great-project"
